// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdkexfslutqzwoqfyxil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ka2V4ZnNsdXRxendvcWZ5eGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjk0MDQsImV4cCI6MjA2MjcwNTQwNH0.4QN_AmHofgsoZjjH2nr4NQ7LEZSeV-SN8NNcBTPMt0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});